import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Cookie Stand</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='flex justify-between items-center font-serif p-4 bg-green-300 text-black'>
      <h1 className="text-4xl">Cookie Stand Admin</h1>
        
      </header>

      <main className=''>
        
      </main>

      <footer className='p-4 mt-8 bg-gray-500 text-gray-50'>
       
      </footer>
    </>
  )
}
